"""
Enumeration types for Module 2 Threat Engine.
"""

from enum import Enum


class Basis(str, Enum):
    Z = "Z"
    X = "X"


class AttackType(str, Enum):
    NONE = "none"
    NOISE = "noise"
    MITM = "mitm"
    FORGERY = "forgery"
    REPLAY = "replay"
    PNS = "pns"


class SecurityDecision(str, Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"


class SecurityStatus(str, Enum):
    SECURE = "SECURE"
    WARNING = "WARNING"
    THREAT = "THREAT"
    INVALID = "INVALID"


class CHSHStatus(str, Enum):
    STRONG_ENTANGLEMENT = "STRONG_ENTANGLEMENT"
    WEAK_ENTANGLEMENT = "WEAK_ENTANGLEMENT"
    BELL_TEST_FAILED = "BELL_TEST_FAILED"
    DISABLED = "DISABLED"


class DecoyStatus(str, Enum):
    NORMAL = "NORMAL"
    ANOMALOUS = "ANOMALOUS"
    DISABLED = "DISABLED"


class AttackClassification(str, Enum):
    NORMAL = "NORMAL"
    CHANNEL_NOISE = "CHANNEL_NOISE"
    HIGH_QBER = "HIGH_QBER"
    ENTANGLEMENT_DEGRADATION = "ENTANGLEMENT_DEGRADATION"
    MITM_SUSPECTED = "MITM_SUSPECTED"
    CLASSICAL_TAMPERING = "CLASSICAL_TAMPERING"
    REPLAY_SUSPECTED = "REPLAY_SUSPECTED"
    PNS_SUSPECTED = "PNS_SUSPECTED"
    MULTIPLE_INDICATORS = "MULTIPLE_INDICATORS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class ReasonCode(str, Enum):
    QBER_WITHIN_THRESHOLD = "QBER_WITHIN_THRESHOLD"
    QBER_ABOVE_THRESHOLD = "QBER_ABOVE_THRESHOLD"
    CHSH_PASS = "CHSH_PASS"
    CHSH_FAIL = "CHSH_FAIL"
    DECOY_NORMAL = "DECOY_NORMAL"
    DECOY_ANOMALY = "DECOY_ANOMALY"
    NO_SIFTED_BITS = "NO_SIFTED_BITS"
    INSUFFICIENT_SIFTED_BITS = "INSUFFICIENT_SIFTED_BITS"
    ARRAY_LENGTH_MISMATCH = "ARRAY_LENGTH_MISMATCH"
    INVALID_BIT_VALUE = "INVALID_BIT_VALUE"
    INVALID_BASIS_VALUE = "INVALID_BASIS_VALUE"
    BASELINE_NOISE_EXCEEDED = "BASELINE_NOISE_EXCEEDED"
    REPLAY_INDICATOR = "REPLAY_INDICATOR"
    CLASSICAL_TAMPERING_INDICATOR = "CLASSICAL_TAMPERING_INDICATOR"
