/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f5",
        "on-surface-variant": "#45474c",
        "on-secondary": "#ffffff",
        "terminal-bg": "#0F172A",
        "secondary": "#0058be",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2e4",
        "secondary-container": "#2170e4",
        "surface-stroke": "#E2E8F0",
        "on-primary-fixed": "#111c2d",
        "surface": "#fbf8fa",
        "primary-fixed-dim": "#bcc7de",
        "background": "#fbf8fa",
        "primary": "#091426",
        "on-secondary-fixed-variant": "#004395",
        "surface-tint": "#545f73",
        "secondary-fixed-dim": "#adc6ff",
        "secondary-fixed": "#d8e2ff",
        "on-secondary-container": "#fefcff",
        "outline-variant": "#c5c6cd",
        "tertiary": "#041528",
        "outline": "#75777d",
        "primary-fixed": "#d8e3fb",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001a42",
        "on-primary": "#ffffff",
        "surface-container-high": "#eae7e9",
        "data-warning": "#B45309",
        "on-surface": "#1b1b1d",
        "tertiary-fixed": "#d3e4fe",
        "on-primary-fixed-variant": "#3c475a",
        "surface-dim": "#dcd9db",
        "on-tertiary-fixed": "#0b1c30",
        "on-tertiary-container": "#8191a9",
        "surface-bright": "#fbf8fa",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed-variant": "#38485d",
        "on-primary-container": "#8590a6",
        "inverse-primary": "#bcc7de",
        "data-critical": "#B91C1C",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#303032",
        "surface-container": "#f0edef",
        "inverse-on-surface": "#f3f0f2",
        "on-tertiary": "#ffffff",
        "primary-container": "#1e293b",
        "tertiary-container": "#1a2a3e",
        "data-success": "#065F46",
        "surface-container-highest": "#e4e2e4",
        "on-background": "#1b1b1d",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "unit": "4px",
        "space-lg": "24px",
        "sidebar-width": "260px",
        "space-md": "16px",
        "space-sm": "8px",
        "drawer-width": "400px",
        "space-xl": "48px",
        "space-xs": "4px"
      },
      fontFamily: {
        sans: ['Zegion', 'sans-serif'],
        display: ['Zegion', 'sans-serif'],
        heading: ['Zegion', 'sans-serif'],
        body: ['Zegion', 'sans-serif'],
        mono: ['Zegion', 'monospace'],
        "headline-lg-mobile": ["Zegion", "sans-serif"],
        "body-md": ["Zegion", "sans-serif"],
        "data-mono": ["Zegion", "monospace"],
        "headline-md": ["Zegion", "sans-serif"],
        "body-sm": ["Zegion", "sans-serif"],
        "headline-lg": ["Zegion", "sans-serif"],
        "label-mono": ["Zegion", "monospace"],
        "body-lg": ["Zegion", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["20px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
}
