import {
  QuantumSession,
  SecurityMetrics,
  SecurityVerdict,
  PipelineStep,
  QuantumNode,
  SecurityIncident,
  TelemetryLog,
  SystemPerformance,
  HistoricalPoint,
} from '../types/sentinel';

// ─── Initial Sessions ────────────────────────────────────────────────────────
export const INITIAL_SESSIONS: QuantumSession[] = [
  {
    session_id: 'QKD-20260826-0001',
    document_name: 'smart_grid_authorization_token_v4.enc',
    document_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    file_size_kb: 42.8,
    status: 'VERIFIED',
    created_at: '2026-08-26T01:38:12Z',
    updated_at: '2026-08-26T01:38:16Z',
    sender: 'Alice (ALC-01 · Node Alpha)',
    receiver: 'Bob (BOB-01 · Node Beta)',
    arbitrator: 'Arbitrator (ARB-01 · Core Cluster)',
    metrics: {
      qber: 0.024,
      baseline_qber: 0.021,
      hoeffding_threshold: 0.056,
      chsh_score: 2.76,
      classical_limit: 2.00,
      tsirelson_bound: 2.828,
      confidence_level: 0.999,
      alpha: 0.001,
      sifted_bits: 3912,
      error_bits: 94,
      total_pulses: 8192,
    },
    verdict: {
      verdict: 'ACCEPT',
      threat_detected: false,
      threat_type: null,
      reason: 'QBER (2.4%) within Hoeffding statistical bound (5.6%). CHSH (2.76) violates classical Bell limit, proving non-local quantum entanglement without eavesdropper disturbance.',
      evaluated_at: '2026-08-26T01:38:16Z',
      hoeffding_pass: true,
      chsh_pass: true,
      signature_pass: true,
      security_score: 98,
    },
  },
  {
    session_id: 'QKD-20260826-0002',
    document_name: 'defense_telemetry_dispatch_manifest_08.sig',
    document_hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    file_size_kb: 128.4,
    status: 'VERIFIED',
    created_at: '2026-08-26T01:32:05Z',
    updated_at: '2026-08-26T01:32:09Z',

    sender: 'Alice (ALC-01 · Node Alpha)',
    receiver: 'Bob (BOB-01 · Node Beta)',
    arbitrator: 'Arbitrator (ARB-01 · Core Cluster)',
    metrics: {
      qber: 0.028,
      baseline_qber: 0.022,
      hoeffding_threshold: 0.058,
      chsh_score: 2.71,
      classical_limit: 2.00,
      tsirelson_bound: 2.828,
      confidence_level: 0.999,
      alpha: 0.001,
      sifted_bits: 3844,
      error_bits: 108,
      total_pulses: 8192,
    },
    verdict: {
      verdict: 'ACCEPT',
      threat_detected: false,
      threat_type: null,
      reason: 'All quantum security tests verified. Channel error statistics conform to expected fiber attenuation profile.',
      evaluated_at: '2026-08-26T01:32:09Z',
      hoeffding_pass: true,
      chsh_pass: true,
      signature_pass: true,
      security_score: 96,
    },
  },
  {
    session_id: 'QDS-2026-SES-9479',
    document_name: 'financial_interbank_clearing_order_202608.xml',
    document_hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    file_size_kb: 86.2,
    status: 'REJECTED',
    created_at: '2026-08-26T01:21:40Z',
    updated_at: '2026-08-26T01:21:44Z',
    sender: 'Alice (ALC-01 · Node Alpha)',
    receiver: 'Bob (BOB-01 · Node Beta)',
    arbitrator: 'Arbitrator (ARB-01 · Core Cluster)',
    metrics: {
      qber: 0.184,
      baseline_qber: 0.021,
      hoeffding_threshold: 0.054,
      chsh_score: 1.82,
      classical_limit: 2.00,
      tsirelson_bound: 2.828,
      confidence_level: 0.999,
      alpha: 0.001,
      sifted_bits: 3104,
      error_bits: 571,
      total_pulses: 8192,
    },
    verdict: {
      verdict: 'REJECT',
      threat_detected: true,
      threat_type: 'MAN_IN_THE_MIDDLE_EAVESDROPPING',
      reason: 'CRITICAL: Observed QBER (18.4%) heavily exceeds Hoeffding bound (5.4%). CHSH parameter (1.82) collapsed below classical bound (2.00), demonstrating measurement collapse from intercept-resend attack.',
      evaluated_at: '2026-08-26T01:21:44Z',
      hoeffding_pass: false,
      chsh_pass: false,
      signature_pass: false,
      security_score: 12,
    },
  },
  {
    session_id: 'QDS-2026-SES-9475',
    document_name: 'cert_authority_root_key_rotation_token.pem',
    document_hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    file_size_kb: 14.6,
    status: 'REJECTED',
    created_at: '2026-08-26T01:05:18Z',
    updated_at: '2026-08-26T01:05:22Z',
    sender: 'Alice (ALC-01 · Node Alpha)',
    receiver: 'Bob (BOB-01 · Node Beta)',
    arbitrator: 'Arbitrator (ARB-01 · Core Cluster)',
    metrics: {
      qber: 0.038,
      baseline_qber: 0.021,
      hoeffding_threshold: 0.056,
      chsh_score: 2.69,
      classical_limit: 2.00,
      tsirelson_bound: 2.828,
      confidence_level: 0.999,
      alpha: 0.001,
      sifted_bits: 3820,
      error_bits: 145,
      total_pulses: 8192,
    },
    verdict: {
      verdict: 'REJECT',
      threat_detected: true,
      threat_type: 'SIGNATURE_FORGERY_ATTEMPT',
      reason: 'REJECTED: Quantum key sifting and channel integrity passed, but the cryptographic message digest verification failed at Arbitrator cross-check. Forged document signature detected.',
      evaluated_at: '2026-08-26T01:05:22Z',
      hoeffding_pass: true,
      chsh_pass: true,
      signature_pass: false,
      security_score: 34,
    },
  },
  {
    session_id: 'QDS-2026-SES-9470',
    document_name: 'telecom_infrastructure_routing_table.bin',
    document_hash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    file_size_kb: 512.0,
    status: 'VERIFIED',
    created_at: '2026-08-26T00:48:30Z',
    updated_at: '2026-08-26T00:48:35Z',
    sender: 'Alice (ALC-01 · Node Alpha)',
    receiver: 'Bob (BOB-01 · Node Beta)',
    arbitrator: 'Arbitrator (ARB-01 · Core Cluster)',
    metrics: {
      qber: 0.022,
      baseline_qber: 0.020,
      hoeffding_threshold: 0.055,
      chsh_score: 2.78,
      classical_limit: 2.00,
      tsirelson_bound: 2.828,
      confidence_level: 0.999,
      alpha: 0.001,
      sifted_bits: 3950,
      error_bits: 87,
      total_pulses: 8192,
    },
    verdict: {
      verdict: 'ACCEPT',
      threat_detected: false,
      threat_type: null,
      reason: 'Complete verification successful. Nonce freshness validated and zero security bounds breached.',
      evaluated_at: '2026-08-26T00:48:35Z',
      hoeffding_pass: true,
      chsh_pass: true,
      signature_pass: true,
      security_score: 99,
    },
  },
];

// ─── Pipeline Steps ───────────────────────────────────────────────────────────
export const DEFAULT_PIPELINE_STEPS: PipelineStep[] = [
  {
    id: 1,
    name: 'Document Hash',
    short_code: '01',
    description: 'SHA-256 digest computation & canonicalization',
    node: 'Alice (ALC-01)',
    status: 'COMPLETED',
    latency_ms: 1.2,
    details: { algorithm: 'SHA-256', bits: 256 },
  },
  {
    id: 2,
    name: 'Alice State Prep',
    short_code: '02',
    description: 'Encoding signature bits into random qubit bases {|0⟩,|1⟩,|+⟩,|-⟩}',
    node: 'Alice (ALC-01)',
    status: 'COMPLETED',
    latency_ms: 12.4,
    details: { modulation: 'Phase/Polarization', basis_entropy: '0.998' },
  },
  {
    id: 3,
    name: 'EPR Generation',
    short_code: '03',
    description: 'Spontaneous parametric down-conversion (SPDC) pair emission',
    node: 'Quantum Core',
    status: 'COMPLETED',
    latency_ms: 8.6,
    details: { state: '|Φ⁺⟩ = (|00⟩+|11⟩)/√2', rate_mhz: 80 },
  },
  {
    id: 4,
    name: 'Bell Measurement',
    short_code: '04',
    description: 'Joint two-qubit Bell state projection (BSM)',
    node: 'Arbitrator (ARB-01)',
    status: 'COMPLETED',
    latency_ms: 4.8,
    details: { bsm_efficiency: '94.2%', outcomes: '|Ψ⁻⟩, |Ψ⁺⟩' },
  },
  {
    id: 5,
    name: 'Classical Feed-Forward',
    short_code: '05',
    description: 'Authenticated classical transmission of 2-bit BSM outcome',
    node: 'Arbitrator → Bob',
    status: 'COMPLETED',
    latency_ms: 2.1,
    details: { auth_tag: 'Poly1305-AES', latency: '2.1 ms' },
  },
  {
    id: 6,
    name: 'Bob Pauli Correction',
    short_code: '06',
    description: 'Unitary transformation σ_x / σ_z based on BSM feed-forward',
    node: 'Bob (BOB-01)',
    status: 'COMPLETED',
    latency_ms: 1.8,
    details: { gate_fidelity: '99.4%', correction: 'σ_z Applied' },
  },
  {
    id: 7,
    name: 'Measurement & Sifting',
    short_code: '07',
    description: 'Conjugate basis alignment and error reconciliation',
    node: 'Alice & Bob',
    status: 'COMPLETED',
    latency_ms: 14.5,
    details: { sifted_length: '3,912 bits', discarded: '52.3%' },
  },
  {
    id: 8,
    name: 'Verification',
    short_code: '08',
    description: 'Hoeffding bound check, CHSH Bell test, and signature verdict',
    node: 'Threat Engine',
    status: 'COMPLETED',
    latency_ms: 6.2,
    details: { verdict: 'ACCEPT', confidence: '99.9%' },
  },
];

// ─── Quantum Network Nodes ────────────────────────────────────────────────────
export const DEFAULT_NODES: QuantumNode[] = [
  {
    id: 'node-arb-01',
    name: 'Arbitrator (ARB-01)',
    role: 'ARBITRATOR',
    status: 'ONLINE',
    endpoint: 'qds-arb.core.internal:7001',
    latency_ms: 1.4,
    requests_count: 14820,
    last_activity: '12ms ago',
    qubit_fidelity: 0.998,
    memory_buffer_mb: 512,
  },
  {
    id: 'node-alc-01',
    name: 'Alice Transmitter (ALC-01)',
    role: 'SENDER',
    status: 'ACTIVE',
    endpoint: 'qds-alice.node-a.internal:7002',
    latency_ms: 2.1,
    requests_count: 7410,
    last_activity: '4ms ago',
    qubit_fidelity: 0.994,
    memory_buffer_mb: 256,
  },
  {
    id: 'node-bob-01',
    name: 'Bob Receiver (BOB-01)',
    role: 'RECEIVER',
    status: 'ACTIVE',
    endpoint: 'qds-bob.node-b.internal:7003',
    latency_ms: 2.3,
    requests_count: 7410,
    last_activity: '4ms ago',
    qubit_fidelity: 0.992,
    memory_buffer_mb: 256,
  },
  {
    id: 'node-threat-01',
    name: 'Threat Engine (TE-01)',
    role: 'THREAT_ENGINE',
    status: 'ONLINE',
    endpoint: 'qds-threat.analytics.internal:7004',
    latency_ms: 3.8,
    requests_count: 14820,
    last_activity: '8ms ago',
    qubit_fidelity: 0.999,
    memory_buffer_mb: 1024,
  },
];

// ─── Security Incidents ───────────────────────────────────────────────────────
export const DEFAULT_INCIDENTS: SecurityIncident[] = [
  {
    id: 'INC-2026-0829',
    session_id: 'QDS-2026-SES-9479',
    event: 'Active Man-in-the-Middle Optical Eavesdropping Detected',
    severity: 'CRITICAL',
    qber: 0.184,
    chsh: 1.82,
    timestamp: '2026-08-26T01:21:44Z',
    threat_category: 'INTERCEPT_RESEND',
    summary: 'Quantum Bit Error Rate reached 18.4%, exceeding Hoeffding statistical limit of 5.4%. CHSH Bell score dropped to 1.82 (violating quantum bound > 2.0). Intercept-resend attack signature positively confirmed.',
    evidence: {
      qber_observed: 0.184,
      hoeffding_threshold: 0.054,
      chsh_score: 1.82,
      classical_limit: 2.00,
      statistical_p_value: 0.00001,
      affected_qubits: 571,
    },
    detection_timeline: [
      { step: 'Session Initialization', time: '01:21:40.002', state: 'PASS', detail: 'Parameters negotiated with Arbitrator' },
      { step: 'EPR Pair Emission', time: '01:21:40.410', state: 'PASS', detail: '8,192 entangled pairs distributed over fiber' },
      { step: 'Bell Measurement', time: '01:21:41.120', state: 'PASS', detail: 'BSM performed by Arbitrator' },
      { step: 'QBER Sifting & Analysis', time: '01:21:42.890', state: 'FAIL', detail: 'Error rate measured at 18.4% (Threshold: 5.4%)' },
      { step: 'CHSH Bell Inequality Test', time: '01:21:43.600', state: 'FAIL', detail: 'CHSH score 1.82 < 2.000. Classical correlation detected' },
      { step: 'Verdict Engine Execution', time: '01:21:44.110', state: 'FAIL', detail: 'Session rejected and security alert dispatched' },
    ],
    final_assessment: 'Threat mitigated at the quantum physical layer. No decrypted key material or valid signature token was exposed to the adversary.',
  },
  {
    id: 'INC-2026-0824',
    session_id: 'QDS-2026-SES-9475',
    event: 'Digital Signature Digest Forgery Detected',
    severity: 'HIGH',
    qber: 0.038,
    chsh: 2.69,
    timestamp: '2026-08-26T01:05:22Z',
    threat_category: 'FORGERY_CROSS_CHECK',
    summary: 'Quantum physical channel remained intact, but canonical SHA-256 document payload digest mismatched Alice signed token during verification at Arbitrator cross-check.',
    evidence: {
      qber_observed: 0.038,
      hoeffding_threshold: 0.056,
      chsh_score: 2.69,
      classical_limit: 2.00,
      statistical_p_value: 0.00042,
      affected_qubits: 0,
    },
    detection_timeline: [
      { step: 'Session Initialization', time: '01:05:18.012', state: 'PASS', detail: 'Standard session established' },
      { step: 'Quantum Channel Transmission', time: '01:05:19.450', state: 'PASS', detail: 'QBER 3.8% (within bound 5.6%)' },
      { step: 'CHSH Entanglement Test', time: '01:05:20.100', state: 'PASS', detail: 'CHSH 2.69 (quantum entanglement intact)' },
      { step: 'Digest Reconciliation', time: '01:05:21.800', state: 'FAIL', detail: 'Document hash checksum did not match Alice signature key' },
      { step: 'Security Audit & Invalidation', time: '01:05:22.050', state: 'FAIL', detail: 'Rejected signature; logged audit trail' },
    ],
    final_assessment: 'The forgery attempt was prevented before authorization could take place.',
  },
  {
    id: 'INC-2026-0818',
    session_id: 'QDS-2026-SES-9462',
    event: 'Transient Channel Noise Spike Anomaly',
    severity: 'MEDIUM',
    qber: 0.049,
    chsh: 2.45,
    timestamp: '2026-08-25T23:14:05Z',
    threat_category: 'ENVIRONMENTAL_NOISE',
    summary: 'Elevated fiber optic polarization drift detected. QBER (4.9%) remained marginally under Hoeffding limit (5.5%). Session was cleared with security telemetry flag.',
    evidence: {
      qber_observed: 0.049,
      hoeffding_threshold: 0.055,
      chsh_score: 2.45,
      classical_limit: 2.00,
      statistical_p_value: 0.0310,
      affected_qubits: 188,
    },
    detection_timeline: [
      { step: 'Optical Link Diagnostic', time: '23:14:01.000', state: 'PASS', detail: 'Polarization drift detected on Fiber #2' },
      { step: 'Statistical Analysis', time: '23:14:03.500', state: 'WARN', detail: 'QBER elevated but within statistical variance' },
      { step: 'Verdict', time: '23:14:05.000', state: 'PASS', detail: 'Verified with secondary calibration trigger' },
    ],
    final_assessment: 'Environmental fluctuation confirmed; automated recalibration performed on Alice polarization controller.',
  },
];

// ─── Historical Trend Points (QBER & CHSH) ───────────────────────────────────
export const HISTORICAL_SERIES: HistoricalPoint[] = [
  { time: '00:00', qber: 0.021, baseline: 0.021, hoeffding: 0.055, chsh: 2.78, classical_limit: 2.00, session_id: 'SES-9460' },
  { time: '00:15', qber: 0.023, baseline: 0.021, hoeffding: 0.055, chsh: 2.76, classical_limit: 2.00, session_id: 'SES-9463' },
  { time: '00:30', qber: 0.025, baseline: 0.021, hoeffding: 0.055, chsh: 2.74, classical_limit: 2.00, session_id: 'SES-9467' },
  { time: '00:45', qber: 0.022, baseline: 0.021, hoeffding: 0.055, chsh: 2.78, classical_limit: 2.00, session_id: 'SES-9470' },
  { time: '01:00', qber: 0.038, baseline: 0.021, hoeffding: 0.056, chsh: 2.69, classical_limit: 2.00, session_id: 'SES-9475' },
  { time: '01:15', qber: 0.026, baseline: 0.021, hoeffding: 0.055, chsh: 2.73, classical_limit: 2.00, session_id: 'SES-9477' },
  { time: '01:21', qber: 0.184, baseline: 0.021, hoeffding: 0.054, chsh: 1.82, classical_limit: 2.00, session_id: 'SES-9479' },
  { time: '01:30', qber: 0.028, baseline: 0.021, hoeffding: 0.056, chsh: 2.71, classical_limit: 2.00, session_id: 'SES-9481' },
  { time: '01:38', qber: 0.024, baseline: 0.021, hoeffding: 0.056, chsh: 2.76, classical_limit: 2.00, session_id: 'SES-9482' },
];

// ─── Telemetry Logs ───────────────────────────────────────────────────────────
export const DEFAULT_TELEMETRY_LOGS: TelemetryLog[] = [
  { id: 'LOG-94821', timestamp: '01:38:16.204', subsystem: 'THREAT_ENGINE', event_type: 'VERDICT_EVALUATED', latency_ms: 6.2, status_code: 200, message: 'Verdict: ACCEPT | QBER: 2.4% (Threshold: 5.6%) | CHSH: 2.76' },
  { id: 'LOG-94820', timestamp: '01:38:15.801', subsystem: 'BOB_NODE', event_type: 'MEASUREMENT_SIFTED', latency_ms: 14.5, status_code: 200, message: 'Basis reconciliation completed with Alice. Sifted bits: 3,912' },
  { id: 'LOG-94819', timestamp: '01:38:14.310', subsystem: 'BOB_NODE', event_type: 'PAULI_CORRECTION_APPLIED', latency_ms: 1.8, status_code: 200, message: 'Applied σ_z gate on receiver state based on BSM feed-forward' },
  { id: 'LOG-94818', timestamp: '01:38:13.620', subsystem: 'ARBITRATOR', event_type: 'BELL_MEASUREMENT_DONE', latency_ms: 4.8, status_code: 200, message: 'BSM outcome recorded | Projection: |Ψ⁻⟩ state' },
  { id: 'LOG-94817', timestamp: '01:38:12.980', subsystem: 'QUANTUM_CORE', event_type: 'EPR_DISTRIBUTED', latency_ms: 8.6, status_code: 200, message: '8,192 EPR photon pairs transmitted over entangled channels' },
  { id: 'LOG-94816', timestamp: '01:38:12.110', subsystem: 'ALICE_NODE', event_type: 'STATE_PREPARED', latency_ms: 12.4, status_code: 200, message: 'Modulated random quantum bases for document hash digest' },
  { id: 'LOG-94815', timestamp: '01:38:11.890', subsystem: 'DATABASE', event_type: 'SESSION_PERSISTED', latency_ms: 3.1, status_code: 201, message: 'Quantum session QDS-2026-SES-9482 created in PostgreSQL session store' },
];

// ─── System Performance ───────────────────────────────────────────────────────
export const DEFAULT_PERFORMANCE: SystemPerformance = {
  api_latency_ms: 4.2,
  requests_total: 44890,
  error_rate_pct: 0.02,
  quantum_core_ops_sec: 1250,
  threat_engine_latency_ms: 3.8,
  active_sessions_count: 3,
  verified_signatures_count: 148,
  threats_detected_count: 2,
};
